//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace erminas.SmartAPI.RedDotCmsXmlServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/RDCMSXMLServer/webservice/", ConfigurationName="RedDotCmsXmlServer.IRqlWebService")]
    public interface IRqlWebService {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://tempuri.org/RDCMSXMLServer/message/) of message ExecuteRequest does not match the default value (http://tempuri.org/RDCMSXMLServer/webservice/)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RDCMSXMLServer/action/XmlServer.Execute", ReplyAction="http://tempuri.org/RDCMSXMLServer/webservice/IRqlWebService/ExecuteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        erminas.SmartAPI.RedDotCmsXmlServer.ExecuteResponse Execute(erminas.SmartAPI.RedDotCmsXmlServer.ExecuteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Execute", WrapperNamespace="http://tempuri.org/RDCMSXMLServer/message/", IsWrapped=true)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string sParamA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public object sErrorA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public object sResultInfoA;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(string sParamA, object sErrorA, object sResultInfoA) {
            this.sParamA = sParamA;
            this.sErrorA = sErrorA;
            this.sResultInfoA = sResultInfoA;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteResponse", WrapperNamespace="http://tempuri.org/RDCMSXMLServer/message/", IsWrapped=true)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public object sErrorA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public object sResultInfoA;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(string Result, object sErrorA, object sResultInfoA) {
            this.Result = Result;
            this.sErrorA = sErrorA;
            this.sResultInfoA = sResultInfoA;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRqlWebServiceChannel : erminas.SmartAPI.RedDotCmsXmlServer.IRqlWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RqlWebServiceClient : System.ServiceModel.ClientBase<erminas.SmartAPI.RedDotCmsXmlServer.IRqlWebService>, erminas.SmartAPI.RedDotCmsXmlServer.IRqlWebService {
        
        public RqlWebServiceClient() {
        }
        
        public RqlWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RqlWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RqlWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RqlWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        erminas.SmartAPI.RedDotCmsXmlServer.ExecuteResponse erminas.SmartAPI.RedDotCmsXmlServer.IRqlWebService.Execute(erminas.SmartAPI.RedDotCmsXmlServer.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public string Execute(string sParamA, ref object sErrorA, ref object sResultInfoA) {
            erminas.SmartAPI.RedDotCmsXmlServer.ExecuteRequest inValue = new erminas.SmartAPI.RedDotCmsXmlServer.ExecuteRequest();
            inValue.sParamA = sParamA;
            inValue.sErrorA = sErrorA;
            inValue.sResultInfoA = sResultInfoA;
            erminas.SmartAPI.RedDotCmsXmlServer.ExecuteResponse retVal = ((erminas.SmartAPI.RedDotCmsXmlServer.IRqlWebService)(this)).Execute(inValue);
            sErrorA = retVal.sErrorA;
            sResultInfoA = retVal.sResultInfoA;
            return retVal.Result;
        }
    }
}
