//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace erminas.SmartAPI.OldService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://reddot.de/cms/webservices/navigation/1_1", ConfigurationName="OldService.RqlServiceSoap")]
    public interface RqlServiceSoap {
        
        // CODEGEN: Generating message contract since element name command from namespace http://reddot.de/cms/webservices/navigation/1_1 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://reddot.de/cms/webservices/navigation/1_1/ExecuteString", ReplyAction="*")]
        erminas.SmartAPI.OldService.ExecuteStringResponse ExecuteString(erminas.SmartAPI.OldService.ExecuteStringRequest request);
        
        // CODEGEN: Generating message contract since element name command from namespace http://reddot.de/cms/webservices/navigation/1_1 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://reddot.de/cms/webservices/navigation/1_1/ExecuteInThreadPool", ReplyAction="*")]
        erminas.SmartAPI.OldService.ExecuteInThreadPoolResponse ExecuteInThreadPool(erminas.SmartAPI.OldService.ExecuteInThreadPoolRequest request);
        
        // CODEGEN: Generating message contract since element name command from namespace http://reddot.de/cms/webservices/navigation/1_1 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://reddot.de/cms/webservices/navigation/1_1/Execute", ReplyAction="*")]
        erminas.SmartAPI.OldService.ExecuteResponse Execute(erminas.SmartAPI.OldService.ExecuteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteString", Namespace="http://reddot.de/cms/webservices/navigation/1_1", Order=0)]
        public erminas.SmartAPI.OldService.ExecuteStringRequestBody Body;
        
        public ExecuteStringRequest() {
        }
        
        public ExecuteStringRequest(erminas.SmartAPI.OldService.ExecuteStringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://reddot.de/cms/webservices/navigation/1_1")]
    public partial class ExecuteStringRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string command;
        
        public ExecuteStringRequestBody() {
        }
        
        public ExecuteStringRequestBody(string command) {
            this.command = command;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteStringResponse", Namespace="http://reddot.de/cms/webservices/navigation/1_1", Order=0)]
        public erminas.SmartAPI.OldService.ExecuteStringResponseBody Body;
        
        public ExecuteStringResponse() {
        }
        
        public ExecuteStringResponse(erminas.SmartAPI.OldService.ExecuteStringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://reddot.de/cms/webservices/navigation/1_1")]
    public partial class ExecuteStringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ExecuteStringResult;
        
        public ExecuteStringResponseBody() {
        }
        
        public ExecuteStringResponseBody(string ExecuteStringResult) {
            this.ExecuteStringResult = ExecuteStringResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteInThreadPoolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteInThreadPool", Namespace="http://reddot.de/cms/webservices/navigation/1_1", Order=0)]
        public erminas.SmartAPI.OldService.ExecuteInThreadPoolRequestBody Body;
        
        public ExecuteInThreadPoolRequest() {
        }
        
        public ExecuteInThreadPoolRequest(erminas.SmartAPI.OldService.ExecuteInThreadPoolRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://reddot.de/cms/webservices/navigation/1_1")]
    public partial class ExecuteInThreadPoolRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string command;
        
        public ExecuteInThreadPoolRequestBody() {
        }
        
        public ExecuteInThreadPoolRequestBody(string command) {
            this.command = command;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteInThreadPoolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteInThreadPoolResponse", Namespace="http://reddot.de/cms/webservices/navigation/1_1", Order=0)]
        public erminas.SmartAPI.OldService.ExecuteInThreadPoolResponseBody Body;
        
        public ExecuteInThreadPoolResponse() {
        }
        
        public ExecuteInThreadPoolResponse(erminas.SmartAPI.OldService.ExecuteInThreadPoolResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ExecuteInThreadPoolResponseBody {
        
        public ExecuteInThreadPoolResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Execute", Namespace="http://reddot.de/cms/webservices/navigation/1_1", Order=0)]
        public erminas.SmartAPI.OldService.ExecuteRequestBody Body;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(erminas.SmartAPI.OldService.ExecuteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://reddot.de/cms/webservices/navigation/1_1")]
    public partial class ExecuteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string command;
        
        public ExecuteRequestBody() {
        }
        
        public ExecuteRequestBody(string command) {
            this.command = command;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteResponse", Namespace="http://reddot.de/cms/webservices/navigation/1_1", Order=0)]
        public erminas.SmartAPI.OldService.ExecuteResponseBody Body;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(erminas.SmartAPI.OldService.ExecuteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ExecuteResponseBody {
        
        public ExecuteResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RqlServiceSoapChannel : erminas.SmartAPI.OldService.RqlServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RqlServiceSoapClient : System.ServiceModel.ClientBase<erminas.SmartAPI.OldService.RqlServiceSoap>, erminas.SmartAPI.OldService.RqlServiceSoap {
        
        public RqlServiceSoapClient() {
        }
        
        public RqlServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RqlServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RqlServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RqlServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        erminas.SmartAPI.OldService.ExecuteStringResponse erminas.SmartAPI.OldService.RqlServiceSoap.ExecuteString(erminas.SmartAPI.OldService.ExecuteStringRequest request) {
            return base.Channel.ExecuteString(request);
        }
        
        public string ExecuteString(string command) {
            erminas.SmartAPI.OldService.ExecuteStringRequest inValue = new erminas.SmartAPI.OldService.ExecuteStringRequest();
            inValue.Body = new erminas.SmartAPI.OldService.ExecuteStringRequestBody();
            inValue.Body.command = command;
            erminas.SmartAPI.OldService.ExecuteStringResponse retVal = ((erminas.SmartAPI.OldService.RqlServiceSoap)(this)).ExecuteString(inValue);
            return retVal.Body.ExecuteStringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        erminas.SmartAPI.OldService.ExecuteInThreadPoolResponse erminas.SmartAPI.OldService.RqlServiceSoap.ExecuteInThreadPool(erminas.SmartAPI.OldService.ExecuteInThreadPoolRequest request) {
            return base.Channel.ExecuteInThreadPool(request);
        }
        
        public void ExecuteInThreadPool(string command) {
            erminas.SmartAPI.OldService.ExecuteInThreadPoolRequest inValue = new erminas.SmartAPI.OldService.ExecuteInThreadPoolRequest();
            inValue.Body = new erminas.SmartAPI.OldService.ExecuteInThreadPoolRequestBody();
            inValue.Body.command = command;
            erminas.SmartAPI.OldService.ExecuteInThreadPoolResponse retVal = ((erminas.SmartAPI.OldService.RqlServiceSoap)(this)).ExecuteInThreadPool(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        erminas.SmartAPI.OldService.ExecuteResponse erminas.SmartAPI.OldService.RqlServiceSoap.Execute(erminas.SmartAPI.OldService.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public void Execute(string command) {
            erminas.SmartAPI.OldService.ExecuteRequest inValue = new erminas.SmartAPI.OldService.ExecuteRequest();
            inValue.Body = new erminas.SmartAPI.OldService.ExecuteRequestBody();
            inValue.Body.command = command;
            erminas.SmartAPI.OldService.ExecuteResponse retVal = ((erminas.SmartAPI.OldService.RqlServiceSoap)(this)).Execute(inValue);
        }
    }
}
